kind: Deployment
apiVersion: apps/v1
metadata:
  name: react-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: react-docker
  template:
    metadata:
      labels:
        app: react-docker
    spec:
      containers:
      - name: react-docker
        image: parmindersingh07/react-docker:0.2
        ports:
        - containerPort: 3000
        env:
          - name: VITE_API_URL
            value: "Hello from the environment"
          - name: VITE_KG_URL
            value: "Such a sweet sorrow 1"
          - name: API_URL
            value: "Hello from the environment"
          - name: KG_URL
            value: "Such a sweet sorrow 1"  